services:
  - title: "Проектирование"
    description: "Создаём решения, которые становятся бенчмарком для отрасли"
    secondDescription: "Информационная архитектура, user flow, прототипы, ux-тесты и проектный контроль"

  - title: "Дизайн интерфейсов"
    description: "Создаём решения, которые становятся бенчмарком для отрасли"
    secondDescription: "Дизайн-концепции, дизайн-системы, контроль на этапе реализации"

  - title: "Исследования"
    description: "Создаём решения, которые становятся бенчмарком для отрасли"
    secondDescription: "Анализ метрик, основных user flow и эргономики интерфейса"

  - title: "UX/UI аудит"
    description: "Создаём решения, которые становятся бенчмарком для отрасли"
    secondDescription: "Проверка гипотез, глубинные интервью и опросы, ux-тесты, работа со стейкхолдерами"
