services:
  - title: "Дизайн интерфейсов"
    description: "Создаём современные визуальные решения и логично структурируем все элементы интерфейса"
    secondDescription: "UX/UI-дизайн. Концепции. Дизайн-системы. Проектный контроль"

  - title: "Проектирование"
    description: "Продумываем взаимодействие пользователя с продуктом, разрабатываем концепцию, проектируем пользовательский путь"
    secondDescription: "Информационная архитектура. Прототипы. User flow. UX-тексты"

  - title: "Исследования"
    description: "Собираем и анализируем данные от пользователей и используем их в работе над продуктом"
    secondDescription: "Проверка гипотез. Глубинные интервью и опросы. Ux-тесты. Общение со стейкхолдерами"

  - title: "UX/UI аудит"
    description: "Анализируем, насколько качественно дизайн выполняет свою функцию"
    secondDescription: "Анализ метрик, user flow и эргономики интерфейса"
